language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-21.0.2
    - android-21
    - sys-img-armeabi-v7a-android-21
    - extra
  
script: ant debug install test

notifications:
  email: false